### ISSUE TITLE
Demo link not working

### ISSUE THREAD

**Issue by goranGG** [mikemajesty/cachorro-dual-list#2]
Hi,
I'm unable to access "Try it yourself" due error:

[Vue warn]: Invalid default value for prop "options": Props with type Object/Array must use a factory function to return the default value. 
(found in <VueDualList> at /home/mike/Projects/vue-dual-list/component/vue-dual-list.vue)

**Comment by mikemajesty** [comment]
https://vue-dual-list.herokuapp.com/
